### ISSUE TITLE
Add support for MacOS on CRAN

### ISSUE THREAD

**Issue by andrie** [andrie/rrd#13]
Although the package builds on MacOS with homebrew, it fails on [CRAN](https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/rrd-00install.html) with:

```
* installing *source* package ‘rrd’ ...
** package ‘rrd’ successfully unpacked and MD5 sums checked
** using staged installation
Package librrd was not found in the pkg-config search path.
Perhaps you should add the directory containing `librrd.pc'
to the PKG_CONFIG_PATH environment variable
No package 'librrd' found
```

To fix this, @jeroen recommends:

> If you want to fix that the official way is opening an issue here https://github.com/r-macos/recipes

**Comment by jeroen** [comment]
This should have been fixed already in https://github.com/andrie/rrd/commit/9021651a10b583ff7b186c397f0373fc247f3535

**Comment by jeroen** [comment]
All ok now: https://cran.r-project.org/web/packages/rrd/index.html

**Comment by andrie** [comment]
Many thanks for your work on this, Jeroen!
